# Fixed-lag smoother configuration
optimization_frequency: 2
transaction_timeout: 0.01
lag_duration: 5.0

motion_models:
  unicycle_motion_model:
    type: fuse_models::Unicycle2D

unicycle_motion_model:
  #                         x      y      yaw    vx     vy     vyaw   ax   ay
  process_noise_diagonal: [0.100, 0.100, 0.100, 0.100, 0.100, 0.100, 0.1, 0.1]

sensor_models:
  initial_localization_sensor:
    type: fuse_models::Unicycle2DIgnition
    motion_models: [unicycle_motion_model]
    ignition: true
  odometry_sensor:
    type: fuse_models::Odometry2D
    motion_models: [unicycle_motion_model]
  imu_sensor:
    type: fuse_models::Imu2D
    motion_models: [unicycle_motion_model]
  range_sensor:
    type: fuse_tutorials::RangeSensorModel
    motion_models: [unicycle_motion_model]

initial_localization_sensor:
  publish_on_startup: false

odometry_sensor:
  topic: 'wheel_odom'
  twist_target_frame: 'base_link'
  linear_velocity_dimensions: ['x', 'y']
  angular_velocity_dimensions: ['yaw']

imu_sensor:
  topic: 'imu'
  twist_target_frame: 'base_link'
  angular_velocity_dimensions: ['yaw']

range_sensor:
  {}

publishers:
  filtered_publisher:
    type: fuse_models::Odometry2DPublisher
  beacon_publisher:
    type: fuse_tutorials::BeaconPublisher

filtered_publisher:
  topic: 'odom_filtered'
  base_link_frame_id: 'base_link'
  odom_frame_id: 'odom'
  map_frame_id: 'map'
  world_frame_id: 'map'
  publish_tf: false

beacon_publisher:
  map_frame_id: 'map'
